### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by paireks** [SimonCropp/PandocNet#75]
My question is if the MIT licensing here is correct, because Pandoc itself is GPL version 2 (source: https://github.com/jgm/pandoc/blob/main/COPYRIGHT)?

**Comment by SimonCropp** [comment]
this project does not use any code from Pandoc. nor does it bundle the Pandoc binaries. so why would MIT be problematic?

**Comment by paireks** [comment]
Ok, I see, for some reason I thought it does bundle a binary. Thank you for explaining :)
